### ISSUE TITLE
M1 / ARM64 port of XRG

### ISSUE THREAD

**Issue by niallrmurphy** [mikepj/XRG#11]
Hi,

Could we have a M1 port of XRG please? Tried compiling myself, but alas, have insufficient time to overcome the errors...

**Comment by mikepj** [comment]
Hi Niall. Yes, an ARM update for XRG is in the works and should be available soon. In the meantime, the current version works under Rosetta for most everything with the exception of temperature sensors.

**Comment by mikepj** [comment]
Posted the update:  https://gaucho.software/xrg/
