### ISSUE TITLE
3.0 issues with battery on M1 Big Sur MacBook Pro

### ISSUE THREAD

**Issue by niallrmurphy** [mikepj/XRG#12]
Hi Mike,

Thanks for the M1 native binary -- really appreciated.

Two issues:
1) On launch, XRG says "No Battery Found" in the graph list, and does not provide any configuration items with respect to it (despite of course the machine having a battery).
2) XRG offers to launch the "Energy Saver System Preferences" -- this fails on Big Sure since it has been renamed to "Battery".

NRM

**Comment by mikepj** [comment]
Thanks for the bug report.  I don't have an M1 laptop to test the battery graph on.  Maybe someone else can take a look and submit a PR, or I should have one later this year.

As for issue number 2, I fixed that in the following commit:  cf4f7ab04300173d0186ea8291572158469461c5

Will be released as part of XRG 3.1.

**Comment by mikepj** [comment]
These issues have been fixed in XRG 3.1.
