### ISSUE TITLE
Rx and Tx stats are merged together into a single line in stacked graph mode in net view

### ISSUE THREAD

**Issue by udp-carl** [mikepj/XRG#22]
Between 3.0.0 and 3.1.0, the stats in the stacked graph mode in the Net view went from being on separate lines to a single merged line.  For example, instead of:

6.0K Rx
1.2K Tx

it reads:

6.0K Rx1.2K Tx

I believe this is due to a newline being left out in the transition to using XRGCommon to format.

In 3.1.0, line 198 of XRGNetView.m contains the following:

`[rightText appendFormat:@"%@ Tx", [XRGCommon formattedStringForBytes:tx]];`

where it should probably be:

`[rightText appendFormat:@"\n%@ Tx", [XRGCommon formattedStringForBytes:tx]];`

**Comment by mikepj** [comment]
Good catch…  I typically have my receive packets inverted from the top, so I didn't notice it.  Checked-in a fix in the `main` branch that should be in the next release.
