### ISSUE TITLE
Improvement: Better legibility for graph lines

### ISSUE THREAD

**Issue by superevr** [mikepj/XRG#23]
For consideration, I think thicker and more rounded graph lines are more legible. I tried to get it to look more like Mx Power Gadget.

https://github.com/mikepj/XRG/blob/83b850acd1664301dee696346ced941fa1de63f1/Graph%20Views/XRGGenericView.m#L157-L160

```
    [bp setLineWidth:1.2f];
    [bp setFlatness: 10.0f];
    [bp setLineCapStyle:NSRoundLineCapStyle];
    [bp setLineJoinStyle:NSRoundLineJoinStyle];
```
XRG default vs thick and round
<img width="295" alt="XRG default vs thick and round" src="https://user-images.githubusercontent.com/2046483/201412402-dd842e7a-4ef2-4179-b09c-3dc50764ab39.png">

Mx Power Gadget
<img width="375" alt="Mx Power Gadget" src="https://user-images.githubusercontent.com/2046483/201412784-6c2938d5-0ffe-4047-8139-93848af295e5.png">

No pull request because I have no idea what I'm doing. This change only affected the GPU and sensor graphs, not the CPU or network graphs.

**Comment by mikepj** [comment]
Sorry it took me so long to respond to this.  I agree, this style looks much better for the lines.  I adapted your code to make it only apply for the line graphs and not the filled graphs.  

Commit:  https://github.com/mikepj/XRG/commit/ad1cdfdeef3fd703aaf225f57f4bccb7848de24c

This will go into the next release.  Closing this as resolved.
