### ISSUE TITLE
Graph text anti-aliasing is inconsistent

### ISSUE THREAD

**Issue by dogcow** [mikepj/XRG#24]
I see two bugs:
1. No text in the graphs respect the "Appearance > Graph Text > Anti-alias" checkbox.
2. Some text in the graphs respect the "General > Graph Window General Appearance > Enable Anti-Aliasing When Drawing Graphs" checkbox, I would expect all graph text to be controlled by the "Appearance > Graph Text > Anti-alias" checkbox.

Fields affected by item 2 are:
  - All text in the GPU graph
  - Right-most numbers in the Net graph
  - Right-most numbers in the Disk graph

![Screenshot 2023-03-09 at 11 58 44 AM](https://user-images.githubusercontent.com/612123/224130971-25865ce5-f308-4085-b9eb-39ef6f60e706.png)

**Comment by mikepj** [comment]
Going to close this as wontfix.  Sorry to remove this feature, but later versions of macOS don't support custom anti-aliasing settings for NSTextFields, which XRG will now use for drawing a lot of the text in the graph window.  Unfortunately the only way to keep text anti-aliasing configurable would be to return to a slower text drawing method.  In order for text to be consistent across all the views, I'm removing the option to disable anti-aliasing for graph text.  This change will take place in XRG version 3.2.1.

Thanks for the the bug report.  Sorry it's probably not the outcome you were looking for.

**Comment by dogcow** [comment]
Losing custom anti-aliasing provided by those checkboxes is fine.  :)

I would like to point out that with the latest release the text circled above is still rendered _differently_ than the rest of the text.  It would be nice to have the rendering consistent between graphs.

**Comment by mikepj** [comment]
I've corrected the GPU graph.  The network and disk graphs use different logic to draw because they have bottom-aligned text.  It's a bigger refactor to fix that one.
